---
name: "Setup LOLCODE"
author: Yevhen Fabizhevskyi
description: "This action sets up a LOLCODE interpreter called LCI."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "LCI version."
    required: false
    default: "0.11.2"
runs:
  using: "composite"
  steps:
    - name: Fail
      if: ${{ runner.os == 'Windows' }}
      run: echo "::error::${RUNNER_OS} ${RUNNER_ARCH} is not supported" && exit 1
      shell: sh
    - name: Collect info
      id: info
      run: |
        lci_installed=$(if command -v lci >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "lci-installed=${lci_installed}" >> "$GITHUB_OUTPUT"
        lci_path="$GITHUB_WORKSPACE/lci"
        mkdir -p "${lci_path}"
        echo "lci-path=${lci_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download LCI
      if: ${{ steps.info.outputs.lci-installed == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: justinmeza/lci
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: lci
    - name: Install LCI
      if: ${{ steps.info.outputs.lci-installed == 'false' }}
      run: |
        cmake .
        make
        echo "${{ steps.info.outputs.lci-path }}" >> "$GITHUB_PATH"
      shell: sh
      working-directory: ${{ steps.info.outputs.lci-path }}
