---
name: 'Setup LOLCODE'
author: Yevhen Fabizhevskyi
description: 'This action sets up a LOLCODE interpreter called LCI.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'LCI version.'
    required: false
    default: '0.11.2'
runs:
  using: 'composite'
  steps:
    - name: Collect info
      id: info
      run: |
        LCI_INSTALLED=$(if command -v lci >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "LCI_INSTALLED=$LCI_INSTALLED" >> $GITHUB_OUTPUT
        lci_path="$GITHUB_WORKSPACE/lci"
        mkdir -p $lci_path
        echo "LCI_PATH=$lci_path" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download LCI
      if: ${{ steps.info.outputs.LCI_INSTALLED == 'false' }}
      uses: actions/checkout@v3
      with:
        repository: justinmeza/lci
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: lci
    - name: Build LCI
      if: ${{ steps.info.outputs.LCI_INSTALLED == 'false' }}
      run: |
        cmake .
        make
      shell: sh
      working-directory: ${{ steps.info.outputs.LCI_PATH }}
    - name: Add LCI to PATH
      if: ${{ steps.info.outputs.LCI_INSTALLED == 'false' }}
      run: |
        exe_path=$(find "${{ steps.info.outputs.LCI_PATH }}" -name "lci")
        echo "exe_path: $exe_path"
        bin_path=$(dirname $exe_path)
        echo "$bin_path" >> $GITHUB_PATH
      shell: sh
