---
name: 'Setup LOLCODE'
author: Yevhen Fabizhevskyi
description: 'This action sets up a LOLCODE interpreter called LCI.'
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: 'LCI version.'
    required: false
    default: '0.11.2'
runs:
  using: 'composite'
  steps:
    - name: Fail
      uses: actions/github-script@v6
      if: ${{ runner.os == 'Windows' }}
      with:
        script: core.setFailed('${{ runner.os }} ${{ runner.arch }} is not supported');
    - name: Collect info
      id: info
      if: ${{ runner.os != 'Windows' }}
      run: |
        LCI_INSTALLED=$(if command -v lci >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "LCI_INSTALLED=$LCI_INSTALLED" >> $GITHUB_OUTPUT
        lci_path="$GITHUB_WORKSPACE/lci"
        mkdir -p $lci_path
        echo "LCI_PATH=$lci_path" >> $GITHUB_OUTPUT
      shell: sh
    - name: Download LCI
      if: ${{ runner.os != 'Windows' && steps.info.outputs.LCI_INSTALLED == 'false' }}
      uses: actions/checkout@v3
      with:
        repository: justinmeza/lci
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: lci
    - name: Install LCI
      if: ${{ runner.os != 'Windows' && steps.info.outputs.LCI_INSTALLED == 'false' }}
      run: |
        cmake .
        make
        echo "${{ steps.info.outputs.LCI_PATH }}" >> $GITHUB_PATH
      shell: sh
      working-directory: ${{ steps.info.outputs.LCI_PATH }}
