---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-**'
      - 'feature-**'

jobs:
  functional_tests:
    name: Run script
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - os: 'ubuntu-latest'
            version: '0.9.2'
          - os: 'ubuntu-latest'
            version: '0.9.3'
          - os: 'ubuntu-latest'
            version: '0.10.1'
          - os: 'ubuntu-latest'
            version: '0.10.2'
          - os: 'ubuntu-latest'
            version: '0.10.3'
          - os: 'ubuntu-latest'
            version: '0.10.4'
          - os: 'ubuntu-latest'
            version: '0.10.5'
          - os: 'ubuntu-latest'
            version: '0.11.1'
          - os: 'ubuntu-latest'
            version: '0.11.2'
          - os: 'macos-latest'
            version: '0.9.2'
          - os: 'macos-latest'
            version: '0.9.3'
          - os: 'macos-latest'
            version: '0.10.5'
          - os: 'macos-latest'
            version: '0.11.2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Cache node_modules
        id: yarn-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Compile
        if: ${{ steps.yarn-cache.outputs.cache-hit != 'true' }}
        run: yarn install --ignore-scripts
      - name: Build
        run: yarn run build
      - name: Setup LCI
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: lci ./hello-world.lc
