---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
      - 'fix-**'
      - 'feature-**'

jobs:
  run-script:
    name: Run script
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'ubuntu-latest'
            version: '0.9.2'
          - os: 'ubuntu-latest'
            version: '0.9.3'
          - os: 'ubuntu-latest'
            version: '0.10.1'
          - os: 'ubuntu-latest'
            version: '0.10.2'
          - os: 'ubuntu-latest'
            version: '0.10.3'
          - os: 'ubuntu-latest'
            version: '0.10.4'
          - os: 'ubuntu-latest'
            version: '0.10.5'
          - os: 'ubuntu-latest'
            version: '0.11.1'
          - os: 'ubuntu-latest'
            version: '0.11.2'
          - os: 'macos-latest'
            version: '0.9.2'
          - os: 'macos-latest'
            version: '0.9.3'
          - os: 'macos-latest'
            version: '0.10.5'
          - os: 'macos-latest'
            version: '0.11.2'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup LCI
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Run script
        run: lci ./hello-world.lc
